vcs:
  type: git
agents:
  available:
  - copilot
  auto_commit: true
project:
  uuid: 10797660-ae0f-41ea-93ee-46b8a631d28e
  slug: premura
  node_id: e2cec46c2bc7
  build_id: e7b5c25e-05c8-4944-b725-fdb25a69a3df
